# Start from the alpine image
FROM golang:1.16

WORKDIR /usr/src/app/

COPY ./example-backend .

ENV PORT=8080

EXPOSE 8080

RUN go build

RUN go test .

ENV REQUEST_ORIGIN=http://localhost:5000

ENTRYPOINT [ "./server" ] 