# Start from the alpine image
FROM node:14-alpine

ENV REACT_APP_BACKEND_URL="http://localhost:8080"
EXPOSE 5000
WORKDIR /usr/src/app/

COPY ./example-frontend .

RUN npm install

RUN npm run build


RUN npm install -g serve

ENTRYPOINT [ "serve", "-s", "-l", "5000", "build" ] 