# Start from the alpine image
FROM ubuntu:22.04

# Use /usr/src/app as our workdir. The following instructions will be executed in this location.
WORKDIR /usr/src/app

# Execute a command with `/bin/sh -c` prefix.
RUN apt update && apt install -y curl && apt upgrade -y

# Copy the script.sh file from this location to /usr/src/app/ creating /usr/src/app/script.sh.
COPY script.sh .

# When running Docker run the command will be ./script.sh
CMD ./script.sh